spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/projetobase
    username: admin
    password: admin
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
  flyway:
    enabled: true
    locations: classpath:db/migration

jwt:
  secret: "my-secret-key-123456"
  expiration: 86400000 # 1 dia